services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-iceberg:
    image: tabulario/spark-iceberg
    container_name: spark-iceberg
    depends_on:
      - rest
      - minio
    volumes:
      - ./data:/data
      - ./notebooks:/notebooks
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - SPARK_CONF_spark_sql_catalog_rest_uri=http://rest:8181
      - SPARK_CONF_spark_sql_catalog_rest=org.apache.iceberg.spark.SparkCatalog
      - SPARK_CONF_spark_sql_catalog_rest_type=rest
      - SPARK_CONF_spark_sql_catalog_rest_warehouse=s3://warehouse/
      - SPARK_CONF_spark_sql_catalog_rest_io-impl=org.apache.iceberg.aws.s3.S3FileIO
      - SPARK_CONF_spark_sql_catalog_rest_s3_endpoint=http://minio:9000
    ports:
      - "8080:8080"
      - "8888:8888"

  rest:
    image: tabulario/iceberg-rest
    container_name: iceberg-rest
    depends_on:
      - minio
    ports:
      - "8181:8181"
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
      - CATALOG_WAREHOUSE=s3://warehouse/
      - CATALOG_IO__IMPL=org.apache.iceberg.aws.s3.S3FileIO
      - CATALOG_S3_ENDPOINT=http://minio:9000
      - CATALOG_S3_PATH__STYLE__ACCESS=true

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set minio http://minio:9000 admin password); do sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      exit 0;
      "
